# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26827e32dcee0a498d9e492ac85f66bf6c130d70468acd7e9323e5dd3b3493c4d053a5c46a358e9973bde5327b17e7de222bb997d9ec9030f7de901575b70270

test:
  secret_key_base: a3e48170a8528db8a67ded1a1f83c3987ddcf39133fbda28a41d2f72fa694e9bbdc314a1772c77031dff1e3704cad31f1d7b5940ff41a210ad1a322ad3cf7592

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
